---
- name: Create user
  hosts: usr
  become: yes
  become_user: root
  vars_files:
    - usr.yml
  tasks:
    - name: refresh inventory
      meta: refresh_inventory
    - name: Create user
      user:
          name: "{{ user_name }}" 
          create_home: yes
          password: "{{ user_passwd | password_hash('sha512') }}"
          state: "{{ user_state }}"
